name: Deployment
on:
  push:
    branches: ["main"]
permissions:
  contents: read
jobs:
  build_and_deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3
    - uses: coursier/cache-action@v6.3
    - uses: VirtusLab/scala-cli-setup@v1.0.1
    - run: mkdir -p out
    - run: scala-cli --power package my-function/my-function.scala -o out/hello.jar --assembly --preamble=false
    - uses: hashicorp/terraform-cdk-action@v0.1.26
      with:
        working-directory: infrastructure
        terraformVersion: 1.4.6
        cdktfVersion: 0.16.3
        stackName: my-function
        mode: auto-approve-apply
